function job=gab_emptyjob
%makes a empty job with required fields, initialized to defaults

job=struct(... %intitialize structure
    'jobName','',...
    'jobDir','',...
    'parent',{{}},...
    'task',{{}},...
    'results',{{}},...
    'status','new',...
    'jid',[],...
    'runTime',[],...
    'error',[]);